const dataPlans = [
    { Value: "500MB", Service: "MTNSME", DataPlan: "500W", Description: "MTN SME Data", Validity: "7-Days", PortalOwners: "₦490", Resellers: "₦495", Agents: "₦500", FreeUsers: "₦505", Status: "Active" },
    { Value: "10GB", Service: "MTNSME", DataPlan: "10000", Description: "MTN SME Data", Validity: "30-Days", PortalOwners: "₦4470", Resellers: "₦4475", Agents: "₦4480", FreeUsers: "₦4485", Status: "Active" },
    { Value: "11GB", Service: "MTNSME", DataPlan: "11000", Description: "MTN SME Data", Validity: "30-Days", PortalOwners: "₦-100", Resellers: "₦-95", Agents: "₦-90", FreeUsers: "₦-85", Status: "Disabled" },
    { Value: "1.5GB", Service: "MTNSME", DataPlan: "1500W", Description: "MTN SME Data", Validity: "7-Days", PortalOwners: "₦975", Resellers: "₦980", Agents: "₦985", FreeUsers: "₦990", Status: "Active" },
    { Value: "6GB", Service: "MTNSME", DataPlan: "6000W", Description: "MTN SME Data", Validity: "7-Days", PortalOwners: "₦2460", Resellers: "₦2465", Agents: "₦2470", FreeUsers: "₦2475", Status: "Active" },
    { Value: "1GB", Service: "MTNSME", DataPlan: "1000D", Description: "MTN SME Data", Validity: "7-Days", PortalOwners: "₦780", Resellers: "₦785", Agents: "₦790", FreeUsers: "₦795", Status: "Active" },
    { Value: "2GB", Service: "MTNSME", DataPlan: "2000", Description: "MTN SME Data", Validity: "30-Days", PortalOwners: "₦1540", Resellers: "₦1545", Agents: "₦1550", FreeUsers: "₦1555", Status: "Active" },
    { Value: "3GB", Service: "MTNSME", DataPlan: "3000", Description: "MTN SME Data", Validity: "30-Days", PortalOwners: "₦2310", Resellers: "₦2315", Agents: "₦2320", FreeUsers: "₦2325", Status: "Active" },
    { Value: "3.5GB", Service: "MTNSME", DataPlan: "3500", Description: "MTN SME Data", Validity: "30-Days", PortalOwners: "₦2450", Resellers: "₦2455", Agents: "₦2460", FreeUsers: "₦2465", Status: "Active" },
    { Value: "5GB", Service: "MTNSME", DataPlan: "5000", Description: "MTN SME Data", Validity: "30-Days", PortalOwners: "₦3850", Resellers: "₦3855", Agents: "₦3860", FreeUsers: "₦3865", Status: "Active" },
    { Value: "7GB", Service: "MTNSME", DataPlan: "7000", Description: "MTN SME Data", Validity: "30-Days", PortalOwners: "₦3450", Resellers: "₦3455", Agents: "₦3460", FreeUsers: "₦3465", Status: "Active" },
    { Value: "500MB", Service: "MTNAWOOF", DataPlan: "500D", Description: "MTN Awoof Data", Validity: "1-Day", PortalOwners: "₦690", Resellers: "₦695", Agents: "₦700", FreeUsers: "₦705", Status: "Active" },
    { Value: "1.4GB", Service: "MTNAWOOF", DataPlan: "1400W", Description: "MTN Awoof Data", Validity: "7-Days", PortalOwners: "₦1756", Resellers: "₦1761", Agents: "₦1766", FreeUsers: "₦1771", Status: "Active" },
    { Value: "7GB", Service: "MTNAWOOF", DataPlan: "7000", Description: "MTN Awoof Data", Validity: "30-Days", PortalOwners: "₦6860", Resellers: "₦6865", Agents: "₦6870", FreeUsers: "₦6875", Status: "Active" },
    { Value: "20GB", Service: "MTNAWOOF", DataPlan: "20000W", Description: "MTN Awoof Data", Validity: "7-Days", PortalOwners: "₦9825", Resellers: "₦9830", Agents: "₦9835", FreeUsers: "₦9840", Status: "Active" },
    { Value: "1.8GB", Service: "MTNAWOOF", DataPlan: "1800", Description: "MTN Awoof Data", Validity: "30-Days", PortalOwners: "₦5865", Resellers: "₦5870", Agents: "₦5875", FreeUsers: "₦5880", Status: "Active" },
    { Value: "10GB", Service: "MTNAWOOF", DataPlan: "10000", Description: "MTN Awoof Data", Validity: "30-Days", PortalOwners: "₦5865", Resellers: "₦5870", Agents: "₦5875", FreeUsers: "₦5880", Status: "Active" },
    { Value: "1GB", Service: "MTNAWOOF", DataPlan: "1000D", Description: "MTN Awoof Data", Validity: "1-Day", PortalOwners: "₦490", Resellers: "₦495", Agents: "₦500", FreeUsers: "₦505", Status: "Active" },
    { Value: "15GB", Service: "MTNAWOOF", DataPlan: "15000", Description: "MTN Awoof Data", Validity: "30-Days (XTRA SPECIAL)", PortalOwners: "₦-100", Resellers: "₦-95", Agents: "₦-90", FreeUsers: "₦-85", Status: "Disabled" },
    { Value: "1.5GB", Service: "MTNAWOOF", DataPlan: "1500D", Description: "MTN Awoof Data", Validity: "2-Days", PortalOwners: "₦590", Resellers: "₦595", Agents: "₦600", FreeUsers: "₦605", Status: "Active" },
    { Value: "500MB", Service: "MTNAWOOF", DataPlan: "500W", Description: "MTN Awoof Data", Validity: "7-Days", PortalOwners: "₦-100", Resellers: "₦-95", Agents: "₦-90", FreeUsers: "₦-85", Status: "Disabled" },
    { Value: "5GB", Service: "MTNAWOOF", DataPlan: "5000W", Description: "MTN Awoof Data", Validity: "7-Days", PortalOwners: "₦-100", Resellers: "₦-95", Agents: "₦-90", FreeUsers: "₦-85", Status: "Disabled" },
    { Value: "6GB", Service: "MTNAWOOF", DataPlan: "6000W", Description: "MTN Awoof Data", Validity: "7-Days", PortalOwners: "₦2430", Resellers: "₦2435", Agents: "₦2440", FreeUsers: "₦2445", Status: "Active" },
    { Value: "11GB", Service: "MTNAWOOF", DataPlan: "11000W", Description: "MTN Awoof Data", Validity: "7-Days", PortalOwners: "₦3400", Resellers: "₦3405", Agents: "₦3410", FreeUsers: "₦3415", Status: "Active" },
    { Value: "5GB", Service: "MTNAWOOF", DataPlan: "5000", Description: "MTN Awoof Data", Validity: "30-Days (XTRA SPECIAL)", PortalOwners: "₦-100", Resellers: "₦-95", Agents: "₦-90", FreeUsers: "₦-85", Status: "Disabled" },
    { Value: "6.75GB", Service: "MTNAWOOF", DataPlan: "6750", Description: "MTN Awoof Data", Validity: "30-Days (XTRA SPECIAL)", PortalOwners: "₦2920", Resellers: "₦2925", Agents: "₦2930", FreeUsers: "₦2935", Status: "Active" },
    { Value: "11GB", Service: "MTNAWOOF", DataPlan: "11000", Description: "MTN Awoof Data", Validity: "30-Days", PortalOwners: "₦-100", Resellers: "₦-95", Agents: "₦-90", FreeUsers: "₦-85", Status: "Disabled" },
    { Value: "40MB", Service: "MTNGIFT", DataPlan: "40", Description: "MTN Gifting Data", Validity: "1-Day", PortalOwners: "₦52", Resellers: "₦57", Agents: "₦62", FreeUsers: "₦67", Status: "Active" },
    { Value: "75MB", Service: "MTNGIFT", DataPlan: "75", Description: "MTN Gifting Data", Validity: "1-Day", PortalOwners: "₦76", Resellers: "₦81", Agents: "₦86", FreeUsers: "₦91", Status: "Active" },
    { Value: "100MB", Service: "MTNGIFT", DataPlan: "100", Description: "MTN Gifting Data", Validity: "1-Day", PortalOwners: "₦101", Resellers: "₦106", Agents: "₦111", FreeUsers: "₦116", Status: "Disabled" },
    { Value: "110MB", Service: "MTNGIFT", DataPlan: "110", Description: "MTN Gifting Data", Validity: "1-Day", PortalOwners: "₦102", Resellers: "₦107", Agents: "₦112", FreeUsers: "₦117", Status: "Disabled" },
    { Value: "230MB", Service: "MTNGIFT", DataPlan: "230", Description: "MTN Gifting Data", Validity: "1-Day", PortalOwners: "₦200", Resellers: "₦205", Agents: "₦210", FreeUsers: "₦215", Status: "Disabled" },
    { Value: "500MB", Service: "MTNGIFT", DataPlan: "500", Description: "MTN Gifting Data", Validity: "7-Days", PortalOwners: "₦490", Resellers: "₦495", Agents: "₦500", FreeUsers: "₦505", Status: "Active" },
    { Value: "750MB", Service: "MTNGIFT", DataPlan: "750", Description: "MTN Gifting Data", Validity: "3-Days", PortalOwners: "₦440", Resellers: "₦445", Agents: "₦450", FreeUsers: "₦455", Status: "Active" },
    { Value: "1GB", Service: "MTNGIFT", DataPlan: "1000D", Description: "MTN Gifting Data", Validity: "1-Day", PortalOwners: "₦490", Resellers: "₦495", Agents: "₦500", FreeUsers: "₦505", Status: "Active" },
    { Value: "1.5GB", Service: "MTNGIFT", DataPlan: "1500D", Description: "MTN Gifting Data", Validity: "2-Days", PortalOwners: "₦590", Resellers: "₦595", Agents: "₦600", FreeUsers: "₦605", Status: "Disabled" },
    { Value: "2GB", Service: "MTNGIFT", DataPlan: "2000D", Description: "MTN Gifting Data", Validity: "2-Days", PortalOwners: "₦735", Resellers: "₦740", Agents: "₦745", FreeUsers: "₦750", Status: "Active" },
    { Value: "2.5GB", Service: "MTNGIFT", DataPlan: "2501D", Description: "MTN Gifting Data", Validity: "1-Day", PortalOwners: "₦735", Resellers: "₦740", Agents: "₦745", FreeUsers: "₦750", Status: "Active" },
    { Value: "2.5GB", Service: "MTNGIFT", DataPlan: "2500D", Description: "MTN Gifting Data", Validity: "2-Days", PortalOwners: "₦880", Resellers: "₦885", Agents: "₦890", FreeUsers: "₦895", Status: "Active" },
    { Value: "3.2GB", Service: "MTNGIFT", DataPlan: "3200D", Description: "MTN Gifting Data", Validity: "2-Days", PortalOwners: "₦980", Resellers: "₦985", Agents: "₦990", FreeUsers: "₦995", Status: "Active" },
    { Value: "1GB", Service: "MTNGIFT", DataPlan: "1000W", Description: "MTN Gifting Data", Validity: "7-Days", PortalOwners: "₦780", Resellers: "₦785", Agents: "₦790", FreeUsers: "₦795", Status: "Active" },
    { Value: "1.5GB", Service: "MTNGIFT", DataPlan: "1500W", Description: "MTN Gifting Data", Validity: "7-Days", PortalOwners: "₦975", Resellers: "₦980", Agents: "₦985", FreeUsers: "₦990", Status: "Active" },
    { Value: "6GB", Service: "MTNGIFT", DataPlan: "6000W", Description: "MTN Gifting Data", Validity: "7-Days", PortalOwners: "₦2415", Resellers: "₦2420", Agents: "₦2425", FreeUsers: "₦2430", Status: "Active" },
    { Value: "2GB", Service: "MTNGIFT", DataPlan: "2000", Description: "MTN Gifting Data", Validity: "30-Days", PortalOwners: "₦1465", Resellers: "₦1470", Agents: "₦1475", FreeUsers: "₦1480", Status: "Active" },
    { Value: "2.7GB", Service: "MTNGIFT", DataPlan: "2700", Description: "MTN Gifting Data", Validity: "30-Days", PortalOwners: "₦1950", Resellers: "₦1955", Agents: "₦1960", FreeUsers: "₦1965", Status: "Active" },
    { Value: "3.5GB", Service: "MTNGIFT", DataPlan: "3500", Description: "MTN Gifting Data", Validity: "30-Days", PortalOwners: "₦2425", Resellers: "₦2430", Agents: "₦2435", FreeUsers: "₦2440", Status: "Active" },
    { Value: "10GB", Service: "MTNGIFT", DataPlan: "10000", Description: "MTN Gifting Data", Validity: "30-Days", PortalOwners: "₦4375", Resellers: "₦4380", Agents: "₦4385", FreeUsers: "₦4390", Status: "Active" },
    { Value: "12.5 GB", Service: "MTNGIFT", DataPlan: "12500", Description: "MTN Gifting Data", Validity: "30-Days", PortalOwners: "₦5430", Resellers: "₦5435", Agents: "₦5440", FreeUsers: "₦5445", Status: "Active" },
    { Value: "5GB", Service: "MTNGIFT", DataPlan: "5000", Description: "MTN Gifting Data", Validity: "30-Day", PortalOwners: "₦2580", Resellers: "₦2585", Agents: "₦2590", FreeUsers: "₦2600", Status: "Active" },
    { Value: "7GB", Service: "MTNGIFT", DataPlan: "7000", Description: "MTN Gifting Data", Validity: "30-Day", PortalOwners: "₦3445", Resellers: "₦3450", Agents: "₦3455", FreeUsers: "₦3460", Status: "Active" },
    { Value: "16.5 GB", Service: "MTNGIFT", DataPlan: "16500", Description: "MTN Gifting Data", Validity: "30-Day", PortalOwners: "₦6355", Resellers: "₦6360", Agents: "₦6365", FreeUsers: "₦6370", Status: "Active" },
    { Value: "20GB", Service: "MTNGIFT", DataPlan: "20000", Description: "MTN Gifting Data", Validity: "30-Days", PortalOwners: "₦7500", Resellers: "₦7505", Agents: "₦7510", FreeUsers: "₦7515", Status: "Active" },
    { Value: "25GB", Service: "MTNGIFT", DataPlan: "25000", Description: "MTN Gifting Data", Validity: "30-Days", PortalOwners: "₦8900", Resellers: "₦8905", Agents: "₦8910", FreeUsers: "₦8915", Status: "Active" },
    { Value: "36GB", Service: "MTNGIFT", DataPlan: "36000", Description: "MTN Gifting Data", Validity: "30-Days", PortalOwners: "₦10800", Resellers: "₦10805", Agents: "₦10810", FreeUsers: "₦10815", Status: "Active" },
    { Value: "75GB", Service: "MTNGIFT", DataPlan: "75000", Description: "MTN Gifting Data", Validity: "30-Days", PortalOwners: "₦17470", Resellers: "₦17480", Agents: "₦17490", FreeUsers: "₦17500", Status: "Active" },
    { Value: "150MB", Service: "AIRTELSME", DataPlan: "150", Description: "Airtel SME Data", Validity: "1-Day", PortalOwners: "₦65", Resellers: "₦70", Agents: "₦75", FreeUsers: "₦80", Status: "Active" },
    { Value: "300MB", Service: "AIRTELSME", DataPlan: "300", Description: "Airtel SME Data", Validity: "2-Days", PortalOwners: "₦114", Resellers: "₦120", Agents: "₦125", FreeUsers: "₦130", Status: "Active" },
    { Value: "600MB", Service: "AIRTELSME", DataPlan: "600", Description: "Airtel SME Data", Validity: "2-Days", PortalOwners: "₦220", Resellers: "₦225", Agents: "₦230", FreeUsers: "₦235", Status: "Active" },
    { Value: "1GB", Service: "AIRTELSME", DataPlan: "1000D", Description: "Airtel SME Data", Validity: "1-Day", PortalOwners: "₦358", Resellers: "₦363", Agents: "₦368", FreeUsers: "₦373", Status: "Active" },
    { Value: "2GB", Service: "AIRTELSME", DataPlan: "2000D", Description: "Airtel SME Data", Validity: "5-Days", PortalOwners: "₦660", Resellers: "₦665", Agents: "₦670", FreeUsers: "₦675", Status: "Active" },
    { Value: "3GB", Service: "AIRTELSME", DataPlan: "3000W", Description: "Airtel SME Data", Validity: "7-Days", PortalOwners: "₦1070", Resellers: "₦1075", Agents: "₦1080", FreeUsers: "₦1085", Status: "Active" },
    { Value: "7GB", Service: "AIRTELSME", DataPlan: "7000W", Description: "Airtel SME Data", Validity: "7-Days", PortalOwners: "₦2035", Resellers: "₦2040", Agents: "₦2045", FreeUsers: "₦2050", Status: "Active" },
    { Value: "4GB", Service: "AIRTELSME", DataPlan: "4000", Description: "Airtel SME Data", Validity: "30-Days", PortalOwners: "₦2450", Resellers: "₦2455", Agents: "₦2460", FreeUsers: "₦2465", Status: "Active" },
    { Value: "10GB", Service: "AIRTELSME", DataPlan: "10000", Description: "Airtel SME Data", Validity: "30-Days", PortalOwners: "₦3100", Resellers: "₦3105", Agents: "₦3110", FreeUsers: "₦3115", Status: "Active" },
    { Value: "13GB", Service: "AIRTELSME", DataPlan: "13000", Description: "Airtel SME Data", Validity: "30-Days", PortalOwners: "₦4925", Resellers: "₦4930", Agents: "₦4935", FreeUsers: "₦4940", Status: "Active" },
    { Value: "100MB", Service: "AIRTELCG", DataPlan: "100", Description: "Airtel Corporate Data", Validity: "7-Days", PortalOwners: "₦105", Resellers: "₦110", Agents: "₦115", FreeUsers: "₦120", Status: "Active" },
    { Value: "300MB", Service: "AIRTELCG", DataPlan: "300", Description: "Airtel Corporate Data", Validity: "7-Days", PortalOwners: "₦270", Resellers: "₦275", Agents: "₦280", FreeUsers: "₦285", Status: "Active" },
    { Value: "500MB", Service: "AIRTELCG", DataPlan: "500", Description: "Airtel Corporate Data", Validity: "30-Days", PortalOwners: "₦490", Resellers: "₦495", Agents: "₦500", FreeUsers: "₦505", Status: "Active" },
    { Value: "1GB", Service: "AIRTELCG", DataPlan: "1000", Description: "Airtel Corporate Data", Validity: "30-Days", PortalOwners: "₦980", Resellers: "₦985", Agents: "₦990", FreeUsers: "₦995", Status: "Active" },
    { Value: "2GB", Service: "AIRTELCG", DataPlan: "2000", Description: "Airtel Corporate Data", Validity: "30-Days", PortalOwners: "₦1960", Resellers: "₦1965", Agents: "₦1970", FreeUsers: "₦1975", Status: "Active" },
    { Value: "5GB", Service: "AIRTELCG", DataPlan: "5000", Description: "Airtel Corporate Data", Validity: "30-Days", PortalOwners: "₦4900", Resellers: "₦4905", Agents: "₦4910", FreeUsers: "₦4915", Status: "Active" },
    { Value: "10GB", Service: "AIRTELCG", DataPlan: "10000", Description: "Airtel Corporate Data", Validity: "30-Days", PortalOwners: "₦9800", Resellers: "₦9805", Agents: "₦9810", FreeUsers: "₦9815", Status: "Active" },
    { Value: "15GB", Service: "AIRTELCG", DataPlan: "15000", Description: "Airtel Corporate Data", Validity: "30-Days", PortalOwners: "₦14700", Resellers: "₦14705", Agents: "₦14710", FreeUsers: "₦14715", Status: "Active" },
    { Value: "20GB", Service: "AIRTELCG", DataPlan: "20000", Description: "Airtel Corporate Data", Validity: "30-Days", PortalOwners: "₦19600", Resellers: "₦19605", Agents: "₦19610", FreeUsers: "₦19615", Status: "Active" },
    { Value: "250GB", Service: "AIRTELCG", DataPlan: "250000", Description: "Airtel Corporate Data", Validity: "30-Days", PortalOwners: "₦250000", Resellers: "₦250005", Agents: "₦250010", FreeUsers: "₦250015", Status: "Active" },
    { Value: "75MB", Service: "AIRTELGIFT", DataPlan: "75", Description: "Airtel Gifting Data", Validity: "1-Day", PortalOwners: "₦79.9", Resellers: "₦84.9", Agents: "₦89.9", FreeUsers: "₦94.9", Status: "Active" },
    { Value: "100MB", Service: "AIRTELGIFT", DataPlan: "100", Description: "Airtel Gifting Data", Validity: "1-Day", PortalOwners: "₦105", Resellers: "₦110", Agents: "₦115", FreeUsers: "₦120", Status: "Disabled" },
    { Value: "200MB", Service: "AIRTELGIFT", DataPlan: "200", Description: "Airtel Gifting Data", Validity: "3-DayS", PortalOwners: "₦206", Resellers: "₦211", Agents: "₦216", FreeUsers: "₦221", Status: "Active" },
    { Value: "300MB", Service: "AIRTELGIFT", DataPlan: "300", Description: "Airtel Gifting Data", Validity: "1-Day", PortalOwners: "₦306", Resellers: "₦311", Agents: "₦316", FreeUsers: "₦321", Status: "Disabled" },
    { Value: "500MB", Service: "AIRTELGIFT", DataPlan: "500", Description: "Airtel Gifting Data", Validity: "3-DayS", PortalOwners: "₦496", Resellers: "₦501", Agents: "₦506", FreeUsers: "₦511", Status: "Active" },
    { Value: "1GB", Service: "AIRTELGIFT", DataPlan: "1000D", Description: "Airtel Gifting Data", Validity: "1-Day", PortalOwners: "₦495", Resellers: "₦500", Agents: "₦505", FreeUsers: "₦510", Status: "Active" },
    { Value: "750MB", Service: "AIRTELGIFT", DataPlan: "750", Description: "Airtel Gifting Data", Validity: "1-Day", PortalOwners: "₦299", Resellers: "₦304", Agents: "₦309", FreeUsers: "₦314", Status: "Disabled" },
    { Value: "1.5GB", Service: "AIRTELGIFT", DataPlan: "1500D", Description: "Airtel Gifting Data", Validity: "2-Days", PortalOwners: "₦595", Resellers: "₦600", Agents: "₦605", FreeUsers: "₦610", Status: "Active" },
    { Value: "3GB", Service: "AIRTELGIFT", DataPlan: "3000D", Description: "Airtel Gifting Data", Validity: "2-Days", PortalOwners: "₦990", Resellers: "₦995", Agents: "₦1000", FreeUsers: "₦1005", Status: "Active" },
    { Value: "5GB", Service: "AIRTELGIFT", DataPlan: "5000D", Description: "Airtel Gifting Data", Validity: "2-Days", PortalOwners: "₦299", Resellers: "₦304", Agents: "₦309", FreeUsers: "₦314", Status: "Disabled" },
    { Value: "1GB", Service: "AIRTELGIFT", DataPlan: "1000W", Description: "Airtel Gifting Data", Validity: "7-Days", PortalOwners: "₦790", Resellers: "₦795", Agents: "₦800", FreeUsers: "₦805", Status: "Active" },
    { Value: "1.5GB", Service: "AIRTELGIFT", DataPlan: "1500W", Description: "Airtel Gifting Data", Validity: "7-Days", PortalOwners: "₦995", Resellers: "₦1000", Agents: "₦1005", FreeUsers: "₦1010", Status: "Active" },
    { Value: "3.5GB", Service: "AIRTELGIFT", DataPlan: "3500W", Description: "Airtel Gifting Data", Validity: "7-Days", PortalOwners: "₦1485", Resellers: "₦1490", Agents: "₦1495", FreeUsers: "₦1500", Status: "Disabled" },
    { Value: "6GB", Service: "AIRTELGIFT", DataPlan: "6000W", Description: "Airtel Gifting Data", Validity: "7-Days", PortalOwners: "₦2493", Resellers: "₦2498", Agents: "₦2503", FreeUsers: "₦2508", Status: "Active" },
    { Value: "10GB", Service: "AIRTELGIFT", DataPlan: "10000W", Description: "Airtel Gifting Data", Validity: "7-Days", PortalOwners: "₦3000", Resellers: "₦3005", Agents: "₦3010", FreeUsers: "₦3015", Status: "Disabled" },
    { Value: "18GB", Service: "AIRTELGIFT", DataPlan: "18000W", Description: "Airtel Gifting Data", Validity: "7-Days", PortalOwners: "₦4975", Resellers: "₦4980", Agents: "₦4985", FreeUsers: "₦4990", Status: "Disabled" },
    { Value: "2GB", Service: "AIRTELGIFT", DataPlan: "2000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦1485", Resellers: "₦1490", Agents: "₦1495", FreeUsers: "₦1500", Status: "Active" },
    { Value: "3GB", Service: "AIRTELGIFT", DataPlan: "3000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦1980", Resellers: "₦1985", Agents: "₦1990", FreeUsers: "₦1995", Status: "Active" },
    { Value: "4GB", Service: "AIRTELGIFT", DataPlan: "4000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦2502", Resellers: "₦2507", Agents: "₦2512", FreeUsers: "₦2517", Status: "Active" },
    { Value: "8GB", Service: "AIRTELGIFT", DataPlan: "8000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦2993", Resellers: "₦2998", Agents: "₦3003", FreeUsers: "₦3008", Status: "Active" },
    { Value: "10GB", Service: "AIRTELGIFT", DataPlan: "10000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦3990", Resellers: "₦3995", Agents: "₦4000", FreeUsers: "₦4005", Status: "Active" },
    { Value: "13GB", Service: "AIRTELGIFT", DataPlan: "13000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦4973", Resellers: "₦4978", Agents: "₦4983", FreeUsers: "₦4988", Status: "Active" },
    { Value: "18GB", Service: "AIRTELGIFT", DataPlan: "18000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦6000", Resellers: "₦6005", Agents: "₦6010", FreeUsers: "₦6015", Status: "Active" },
    { Value: "25GB", Service: "AIRTELGIFT", DataPlan: "25000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦8055", Resellers: "₦8060", Agents: "₦8065", FreeUsers: "₦8070", Status: "Active" },
    { Value: "35GB", Service: "AIRTELGIFT", DataPlan: "35000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦10000", Resellers: "₦10005", Agents: "₦10010", FreeUsers: "₦10015", Status: "Active" },
    { Value: "60GB", Service: "AIRTELGIFT", DataPlan: "60000", Description: "Airtel Gifting Data", Validity: "30-Days", PortalOwners: "₦15275", Resellers: "₦15280", Agents: "₦15285", FreeUsers: "₦15290", Status: "Active" },
    { Value: "50MB", Service: "GLOSME", DataPlan: "50", Description: "GLO SME Data", Validity: "1-Day", PortalOwners: "₦52", Resellers: "₦57", Agents: "₦62", FreeUsers: "₦67", Status: "Active" },
    { Value: "125MB", Service: "GLOSME", DataPlan: "125", Description: "GLO SME Data", Validity: "1-Day", PortalOwners: "₦98", Resellers: "₦103", Agents: "₦108", FreeUsers: "₦113", Status: "Active" },
    { Value: "260MB", Service: "GLOSME", DataPlan: "260", Description: "GLO SME Data", Validity: "2-Days", PortalOwners: "₦192", Resellers: "₦197", Agents: "₦202", FreeUsers: "₦207", Status: "Active" },
    { Value: "350MB", Service: "GLOSME", DataPlan: "350", Description: "GLO SME Data", Validity: "1-Day", PortalOwners: "₦100", Resellers: "₦105", Agents: "₦110", FreeUsers: "₦115", Status: "Active" },
    { Value: "750MB", Service: "GLOSME", DataPlan: "750N", Description: "GLO SME Data", Validity: "1-Night Plan", PortalOwners: "₦119", Resellers: "₦124", Agents: "₦129", FreeUsers: "₦134", Status: "Active" },
    { Value: "750MB", Service: "GLOSME", DataPlan: "750", Description: "GLO SME Data", Validity: "1-Day", PortalOwners: "₦205", Resellers: "₦210", Agents: "₦215", FreeUsers: "₦220", Status: "Active" },
    { Value: "1.25GB", Service: "GLOSME", DataPlan: "1250D", Description: "GLO SME Data", Validity: "1 Sunday Plan", PortalOwners: "₦200", Resellers: "₦205", Agents: "₦210", FreeUsers: "₦215", Status: "Active" },
    { Value: "1.5GB", Service: "GLOSME", DataPlan: "1500D", Description: "GLO SME Data", Validity: "1-Day", PortalOwners: "₦300", Resellers: "₦305", Agents: "₦310", FreeUsers: "₦315", Status: "Active" },
    { Value: "2.5GB", Service: "GLOSME", DataPlan: "2500D", Description: "GLO SME Data", Validity: "2-Days", PortalOwners: "₦500", Resellers: "₦505", Agents: "₦510", FreeUsers: "₦515", Status: "Active" },
    { Value: "3.75GB", Service: "GLOSME", DataPlan: "3750D", Description: "GLO SME Data", Validity: "1-Day", PortalOwners: "₦590", Resellers: "₦595", Agents: "₦600", FreeUsers: "₦605", Status: "Disabled" },
    { Value: "10GB", Service: "GLOSME", DataPlan: "10000W", Description: "GLO SME Data", Validity: "7-Days", PortalOwners: "₦2000", Resellers: "₦2005", Agents: "₦2010", FreeUsers: "₦2015", Status: "Active" },
    { Value: "50MB", Service: "GLOCG", DataPlan: "50", Description: "GLO Corporate Data", Validity: "1-Day", PortalOwners: "₦-485", Resellers: "₦-480", Agents: "₦-475", FreeUsers: "₦-470", Status: "Disabled" },
    { Value: "100MB", Service: "GLOCG", DataPlan: "100", Description: "GLO Corporate Data", Validity: "1-Day", PortalOwners: "₦-485", Resellers: "₦-480", Agents: "₦-475", FreeUsers: "₦-470", Status: "Disabled" },
    { Value: "200MB", Service: "GLOCG", DataPlan: "200", Description: "GLO Corporate Data", Validity: "14-Days", PortalOwners: "₦90", Resellers: "₦95", Agents: "₦100", FreeUsers: "₦105", Status: "Active" },
    { Value: "500MB", Service: "GLOCG", DataPlan: "500", Description: "GLO Corporate Data", Validity: "30-Days", PortalOwners: "₦210", Resellers: "₦215", Agents: "₦220", FreeUsers: "₦225", Status: "Active" },
    { Value: "1GB", Service: "GLOCG", DataPlan: "1000", Description: "GLO Corporate Data", Validity: "30-Days", PortalOwners: "₦408", Resellers: "₦415", Agents: "₦420", FreeUsers: "₦425", Status: "Active" },
    { Value: "2GB", Service: "GLOCG", DataPlan: "2000", Description: "GLO Corporate Data", Validity: "30-Days", PortalOwners: "₦816", Resellers: "₦820", Agents: "₦825", FreeUsers: "₦830", Status: "Active" },
    { Value: "3GB", Service: "GLOCG", DataPlan: "3000", Description: "GLO Corporate Data", Validity: "30-Days", PortalOwners: "₦1225", Resellers: "₦1230", Agents: "₦1235", FreeUsers: "₦1240", Status: "Active" },
    { Value: "4GB", Service: "GLOCG", DataPlan: "4000", Description: "GLO Corporate Data", Validity: "30-Days", PortalOwners: "₦1630", Resellers: "₦1745", Agents: "₦1750", FreeUsers: "₦1755", Status: "Disabled" },
    { Value: "5GB", Service: "GLOCG", DataPlan: "5000", Description: "GLO Corporate Data", Validity: "30-Days", PortalOwners: "₦2040", Resellers: "₦2050", Agents: "₦2055", FreeUsers: "₦2060", Status: "Active" },
    { Value: "10GB", Service: "GLOCG", DataPlan: "10000", Description: "GLO Corporate Data", Validity: "30-Days", PortalOwners: "₦4050", Resellers: "₦4060", Agents: "₦4065", FreeUsers: "₦4070", Status: "Active" },
    { Value: "50MB", Service: "GLOGIFT", DataPlan: "50", Description: "GLO Gifting Data", Validity: "1-Day", PortalOwners: "₦51", Resellers: "₦56", Agents: "₦61", FreeUsers: "₦66", Status: "Active" },
    { Value: "150MB", Service: "GLOGIFT", DataPlan: "150", Description: "GLO Gifting Data", Validity: "1-Day", PortalOwners: "₦97", Resellers: "₦102", Agents: "₦107", FreeUsers: "₦112", Status: "Active" },
    { Value: "350MB", Service: "GLOGIFT", DataPlan: "350", Description: "GLO Gifting Data", Validity: "1-Day", PortalOwners: "₦191", Resellers: "₦196", Agents: "₦201", FreeUsers: "₦206", Status: "Active" },
    { Value: "1GB", Service: "GLOGIFT", DataPlan: "1000W", Description: "GLO Gifting Data", Validity: "14-Days", PortalOwners: "₦470", Resellers: "₦475", Agents: "₦480", FreeUsers: "₦485", Status: "Active" },
    { Value: "3.9GB", Service: "GLOGIFT", DataPlan: "3900", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦945", Resellers: "₦950", Agents: "₦955", FreeUsers: "₦960", Status: "Active" },
    { Value: "7.5GB", Service: "GLOGIFT", DataPlan: "7500", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦2380", Resellers: "₦2385", Agents: "₦2390", FreeUsers: "₦2395", Status: "Active" },
    { Value: "9.2GB", Service: "GLOGIFT", DataPlan: "9000", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦1905", Resellers: "₦1910", Agents: "₦1915", FreeUsers: "₦1920", Status: "Active" },
    { Value: "10.8GB", Service: "GLOGIFT", DataPlan: "10000", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦2865", Resellers: "₦2870", Agents: "₦2875", FreeUsers: "₦2880", Status: "Active" },
    { Value: "14GB", Service: "GLOGIFT", DataPlan: "14000", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦3830", Resellers: "₦3835", Agents: "₦3840", FreeUsers: "₦3845", Status: "Active" },
    { Value: "18GB", Service: "GLOGIFT", DataPlan: "18000", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦4760", Resellers: "₦4765", Agents: "₦4770", FreeUsers: "₦4775", Status: "Active" },
    { Value: "20GB", Service: "GLOGIFT", DataPlan: "20000", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦-4700", Resellers: "₦-4695", Agents: "₦-4690", FreeUsers: "₦-4685", Status: "Disabled" },
    { Value: "27GB", Service: "GLOGIFT", DataPlan: "27000", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦-7460", Resellers: "₦-7455", Agents: "₦-7450", FreeUsers: "₦-7445", Status: "Disabled" },
    { Value: "50GB", Service: "GLOGIFT", DataPlan: "50000", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦-9320", Resellers: "₦-9315", Agents: "₦-9310", FreeUsers: "₦-9305", Status: "Disabled" },
    { Value: "93GB", Service: "GLOGIFT", DataPlan: "93000", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦-13950", Resellers: "₦-13945", Agents: "₦-13940", FreeUsers: "₦-13935", Status: "Disabled" },
    { Value: "119GB", Service: "GLOGIFT", DataPlan: "119000", Description: "GLO Gifting Data", Validity: "30-Days", PortalOwners: "₦-16760", Resellers: "₦-16755", Agents: "₦-16750", FreeUsers: "₦-16745", Status: "Disabled" },
    { Value: "250MB", Service: "9MOBILESME", DataPlan: "250", Description: "9MOBILE SME Data", Validity: "14-Days", PortalOwners: "₦81", Resellers: "₦86", Agents: "₦91", FreeUsers: "₦96", Status: "Active" },
    { Value: "500MB", Service: "9MOBILESME", DataPlan: "500", Description: "9MOBILE SME Data", Validity: "30-Days", PortalOwners: "₦135", Resellers: "₦140", Agents: "₦145", FreeUsers: "₦150", Status: "Active" },
    { Value: "3.5GB", Service: "9MOBILESME", DataPlan: "3500", Description: "9MOBILE SME Data", Validity: "30-Days", PortalOwners: "₦905", Resellers: "₦910", Agents: "₦915", FreeUsers: "₦920", Status: "Active" },
    { Value: "7GB", Service: "9MOBILESME", DataPlan: "7000", Description: "9MOBILE SME Data", Validity: "30-Days", PortalOwners: "₦1750", Resellers: "₦1755", Agents: "₦1760", FreeUsers: "₦1765", Status: "Active" },
    { Value: "15GB", Service: "9MOBILESME", DataPlan: "15000", Description: "9MOBILE SME Data", Validity: "30-Days", PortalOwners: "₦3100", Resellers: "₦3105", Agents: "₦3110", FreeUsers: "₦3115", Status: "Active" },
    { Value: "250MB", Service: "9MOBILECG", DataPlan: "250", Description: "9MOBILE Corporate Data", Validity: "14-Days", PortalOwners: "₦81", Resellers: "₦86", Agents: "₦91", FreeUsers: "₦96", Status: "Disabled" },
    { Value: "500MB", Service: "9MOBILECG", DataPlan: "500", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦147", Resellers: "₦152", Agents: "₦157", FreeUsers: "₦162", Status: "Active" },
    { Value: "1GB", Service: "9MOBILECG", DataPlan: "1000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦285", Resellers: "₦290", Agents: "₦295", FreeUsers: "₦300", Status: "Active" },
    { Value: "1.5GB", Service: "9MOBILECG", DataPlan: "1500", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦435", Resellers: "₦440", Agents: "₦445", FreeUsers: "₦450", Status: "Active" },
    { Value: "2GB", Service: "9MOBILECG", DataPlan: "2000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦570", Resellers: "₦575", Agents: "₦580", FreeUsers: "₦585", Status: "Active" },
    { Value: "3GB", Service: "9MOBILECG", DataPlan: "3000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦855", Resellers: "₦860", Agents: "₦865", FreeUsers: "₦870", Status: "Active" },
    { Value: "4GB", Service: "9MOBILECG", DataPlan: "4000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦1140", Resellers: "₦1145", Agents: "₦1150", FreeUsers: "₦1155", Status: "Active" },
    { Value: "4.5GB", Service: "9MOBILECG", DataPlan: "4500", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦1283", Resellers: "₦1288", Agents: "₦1293", FreeUsers: "₦1298", Status: "Active" },
    { Value: "5GB", Service: "9MOBILECG", DataPlan: "5000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦1425", Resellers: "₦1430", Agents: "₦1435", FreeUsers: "₦1440", Status: "Active" },
    { Value: "10GB", Service: "9MOBILECG", DataPlan: "10000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦2850", Resellers: "₦2855", Agents: "₦2860", FreeUsers: "₦2865", Status: "Active" },
    { Value: "11GB", Service: "9MOBILECG", DataPlan: "11000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦4125", Resellers: "₦4130", Agents: "₦4135", FreeUsers: "₦4140", Status: "Active" },
    { Value: "15GB", Service: "9MOBILECG", DataPlan: "15000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦4275", Resellers: "₦4280", Agents: "₦4285", FreeUsers: "₦4290", Status: "Active" },
    { Value: "20GB", Service: "9MOBILECG", DataPlan: "20000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦5700", Resellers: "₦5705", Agents: "₦5710", FreeUsers: "₦5715", Status: "Active" },
    { Value: "25GB", Service: "9MOBILECG", DataPlan: "25000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦7125", Resellers: "₦7130", Agents: "₦7135", FreeUsers: "₦7140", Status: "Active" },
    { Value: "30GB", Service: "9MOBILECG", DataPlan: "30000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦8550", Resellers: "₦8555", Agents: "₦8560", FreeUsers: "₦8565", Status: "Active" },
    { Value: "40GB", Service: "9MOBILECG", DataPlan: "40000", Description: "9MOBILE Corporate Data", Validity: "30-Days", PortalOwners: "₦11350", Resellers: "₦11355", Agents: "₦11360", FreeUsers: "₦11365", Status: "Active" },
    { Value: "25MB", Service: "9MOBILEGIFT", DataPlan: "25", Description: "9MOBILE Gifting Data", Validity: "1-Day", PortalOwners: "₦87", Resellers: "₦92", Agents: "₦97", FreeUsers: "₦102", Status: "Active" },
    { Value: "1GB", Service: "9MOBILEGIFT", DataPlan: "1000D", Description: "9MOBILE Gifting Data", Validity: "1-Day", PortalOwners: "₦850", Resellers: "₦855", Agents: "₦860", FreeUsers: "₦865", Status: "Disabled" },
    { Value: "2GB", Service: "9MOBILEGIFT", DataPlan: "2000D", Description: "9MOBILE Gifting Data", Validity: "1-Day", PortalOwners: "₦850", Resellers: "₦855", Agents: "₦860", FreeUsers: "₦865", Status: "Active" },
    { Value: "250MB", Service: "9MOBILEGIFT", DataPlan: "250", Description: "9MOBILE Gifting Data", Validity: "7-Days", PortalOwners: "₦334", Resellers: "₦339", Agents: "₦344", FreeUsers: "₦349", Status: "Disabled" },
    { Value: "500MB", Service: "9MOBILEGIFT", DataPlan: "500", Description: "9MOBILE Gifting Data", Validity: "7-Days", PortalOwners: "₦830", Resellers: "₦835", Agents: "₦840", FreeUsers: "₦845", Status: "Disabled" },
    { Value: "100MB", Service: "9MOBILEGIFT", DataPlan: "100", Description: "9MOBILE Gifting Data", Validity: "7-Days", PortalOwners: "₦187", Resellers: "₦192", Agents: "₦197", FreeUsers: "₦202", Status: "Active" },
    { Value: "250MB", Service: "9MOBILEGIFT", DataPlan: "250", Description: "9MOBILE Gifting Data", Validity: "14-Days", PortalOwners: "₦160", Resellers: "₦165", Agents: "₦170", FreeUsers: "₦175", Status: "Active" },
    { Value: "350MB", Service: "9MOBILEGIFT", DataPlan: "350", Description: "9MOBILE Gifting Data", Validity: "7-Days", PortalOwners: "₦594", Resellers: "₦599", Agents: "₦604", FreeUsers: "₦609", Status: "Active" },
    { Value: "1.5GB", Service: "9MOBILEGIFT", DataPlan: "1500W", Description: "9MOBILE Gifting Data", Validity: "7-Days", PortalOwners: "₦705", Resellers: "₦710", Agents: "₦715", FreeUsers: "₦720", Status: "Active" },
    { Value: "7GB", Service: "9MOBILEGIFT", DataPlan: "7000W", Description: "9MOBILE Gifting Data", Validity: "7-Days", PortalOwners: "₦2510", Resellers: "₦2520", Agents: "₦2530", FreeUsers: "₦2540", Status: "Active" },
    { Value: "500MB", Service: "9MOBILEGIFT", DataPlan: "500", Description: "9MOBILE Gifting Data", Validity: "14-Days", PortalOwners: "₦320", Resellers: "₦325", Agents: "₦330", FreeUsers: "₦335", Status: "Active" },
    { Value: "5GB", Service: "9MOBILEGIFT", DataPlan: "5000W", Description: "9MOBILE Gifting Data", Validity: "14-Days", PortalOwners: "₦2350", Resellers: "₦2360", Agents: "₦2370", FreeUsers: "₦2380", Status: "Active" },
    { Value: "1.5GB", Service: "9MOBILEGIFT", DataPlan: "1500", Description: "9MOBILE Gifting Data", Validity: "30-Days", PortalOwners: "₦1660", Resellers: "₦1665", Agents: "₦1670", FreeUsers: "₦1675", Status: "Active" },
    { Value: "2GB", Service: "9MOBILEGIFT", DataPlan: "2000", Description: "9MOBILE Gifting Data", Validity: "30-Days", PortalOwners: "₦1984", Resellers: "₦1994", Agents: "₦2004", FreeUsers: "₦2014", Status: "Active" },
    { Value: "3GB", Service: "9MOBILEGIFT", DataPlan: "3000", Description: "9MOBILE Gifting Data", Validity: "30-Days", PortalOwners: "₦2480", Resellers: "₦2490", Agents: "₦2500", FreeUsers: "₦2510", Status: "Active" },
    { Value: "4.5GB", Service: "9MOBILEGIFT", DataPlan: "4500", Description: "9MOBILE Gifting Data", Validity: "30-Days", PortalOwners: "₦3320", Resellers: "₦3330", Agents: "₦3340", FreeUsers: "₦3350", Status: "Active" },
    { Value: "5.5GB", Service: "9MOBILEGIFT", DataPlan: "5500", Description: "9MOBILE Gifting Data", Validity: "30-Days", PortalOwners: "₦6840", Resellers: "₦6850", Agents: "₦6860", FreeUsers: "₦6870", Status: "Active" },
    { Value: "11GB", Service: "9MOBILEGIFT", DataPlan: "11000", Description: "9MOBILE Gifting Data", Validity: "30-Days", PortalOwners: "₦6630", Resellers: "₦6640", Agents: "₦6650", FreeUsers: "₦6645", Status: "Active" },
    { Value: "15GB", Service: "9MOBILEGIFT", DataPlan: "15000", Description: "9MOBILE Gifting Data", Validity: "30-Days", PortalOwners: "₦8300", Resellers: "₦8310", Agents: "₦8320", FreeUsers: "₦8330", Status: "Active" },
    { Value: "25GB", Service: "9MOBILEGIFT", DataPlan: "25000", Description: "9MOBILE Gifting Data", Validity: "30-Days", PortalOwners: "₦17820", Resellers: "₦17830", Agents: "₦17840", FreeUsers: "₦17850", Status: "Active" }
];

const electricityPlanList = [
  { serviceCode: "aba-electric", displayName: "Aba Electricity Distribution Company" },
  { serviceCode: "abuja-electric", displayName: "Abuja Electricity Distribution Company" },
  { serviceCode: "benin-electric", displayName: "Benin Electricity Distribution Company" },
  { serviceCode: "eko-electric", displayName: "Eko Electricity Distribution Company" },
  { serviceCode: "enugu-electric", displayName: "Enugu Electricity Distribution Company" },
  { serviceCode: "ibadan-electric", displayName: "Ibadan Electricity Distribution Company" },
  { serviceCode: "ikeja-electric", displayName: "Ikeja Electricity Distribution Company" },
  { serviceCode: "jos-electric", displayName: "Jos Electricity Distribution Company" },
  { serviceCode: "kaduna-electric", displayName: "Kaduna Electricity Distribution Company" },
  { serviceCode: "kano-electric", displayName: "Kano Electricity Distribution Company" },
  { serviceCode: "portharcourt-electric", displayName: "Port Harcourt Electricity Distribution Company" },
  { serviceCode: "yola-electric", displayName: "Yola Electricity Distribution Company" }
]

const cablePlans = [
  { name: "gotv_smallie", price: 1900 },
  { name: "gotv_smallie_3months", price: 5100 },
  { name: "gotv_smallie_1year", price: 15000 },
  { name: "gotv_jinja", price: 3900 },
  { name: "gotv_jolli", price: 5800 },
  { name: "gotv_max", price: 8500 },
  { name: "dstv_padi", price: 4400 },
  { name: "dstv_yanga", price: 6000 },
  { name: "dstv_confam", price: 11000 },
  { name: "dstv_compact", price: 19000 },
  { name: "dstv_compact_plus", price: 30000 },
  { name: "dstv_premium", price: 44500 },
  { name: "dstv_asia", price: 14900 },
  { name: "dstv_premium_french", price: 69000 },
  { name: "startimes_nova_daily", price: 0.0 },
  { name: "startimes_nova_weekly", price: 600 },
  { name: "startimes_nova", price: 1900 },
  { name: "startimes_basic_daily", price: 0.0 },
  { name: "startimes_basic_weekly", price: 1250 },
  { name: "startimes_basic", price: 3700 },
  { name: "startimes_smart_daily", price: 0.0 },
  { name: "startimes_smart_weekly", price: 1550 },
  { name: "startimes_smart", price: 4700 },
  { name: "startimes_classic_daily", price: 0.0 },
  { name: "startimes_classic_weekly", price: 1900 },
  { name: "startimes_classic", price: 5500 },
  { name: "startimes_super_daily", price: 0.0 },
  { name: "startimes_super_weekly", price: 3000 },
  { name: "startimes_super", price: 9000 },
  { name: "startimes_unique_daily", price: 0.0 },
  { name: "startimes_unique_weekly", price: 0.0 },
  { name: "startimes_unique", price: 0.0 },
]

const checkResultPlans = [
  { description: "WAEC Result Checking PIN", code: 1 },
  { description: "WAEC GCE Registration PIN", code: 2 },
  { description: "WAEC Verification PIN", code: 3 },
  { description: "NECO Result Checking Token", code: 1 },
  { description: "NECO GCE Registration PIN", code: 2 },
  { description: "NABTEB Result Checking PIN", code: 1 },
  { description: "NABTEB GCE Registration PIN", code: 2 },
  { description: "JAMB UTME Registration PIN", code: 1 },
  { description: "JAMB Direct Entry Registration PIN", code: 2 }
]


export { dataPlans, electricityPlanList, cablePlans, checkResultPlans }
