const dataPlans = [
  // 9MOBILE
  { id: 276, network: "9MOBILE", network_id: 3, planType: "CORPORATE GIFTING", amount: 3700.0, size: "10.0 GB", validity: "1 month" },
  { id: 303, network: "9MOBILE", network_id: 3, planType: "CORPORATE GIFTING", amount: 1500.0, size: "4.0 GB", validity: "1 month" },
  { id: 273, network: "9MOBILE", network_id: 3, planType: "CORPORATE GIFTING", amount: 1200.0, size: "3.0 GB", validity: "1 month" },
  { id: 297, network: "9MOBILE", network_id: 3, planType: "CORPORATE GIFTING", amount: 7400.0, size: "20.0 GB", validity: "1 Month" },
  { id: 324, network: "9MOBILE", network_id: 3, planType: "CORPORATE GIFTING", amount: 5600.0, size: "15.0 GB", validity: "1MONTH" },
  { id: 270, network: "9MOBILE", network_id: 3, planType: "CORPORATE GIFTING", amount: 400.0, size: "1.0 GB", validity: "1 month" },
  { id: 275, network: "9MOBILE", network_id: 3, planType: "CORPORATE GIFTING", amount: 1250.0, size: "5.0 GB", validity: "1 month" },
  { id: 302, network: "9MOBILE", network_id: 3, planType: "CORPORATE GIFTING", amount: 200.0, size: "500.0 MB", validity: "1 Month" },
  { id: 271, network: "9MOBILE", network_id: 3, planType: "CORPORATE GIFTING", amount: 800.0, size: "2.0 GB", validity: "1 Month" },

  // AIRTEL
  { id: 307, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 3000.0, size: "8.0 GB", validity: "1 Month" },
  { id: 249, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 5200.0, size: "5.0 GB", validity: "30DAYS" },
  { id: 340, network: "AIRTEL", network_id: 4, planType: "SME", amount: 600.0, size: "2.0 GB", validity: "2DAYS" },
  { id: 150, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 4950.0, size: "13.0 GB", validity: "30 days" },
  { id: 343, network: "AIRTEL", network_id: 4, planType: "SME", amount: 3500.0, size: "10.0 GB", validity: "30DAY" },
  { id: 376, network: "AIRTEL", network_id: 4, planType: "SME", amount: 80.0, size: "150.0 MB", validity: "1DAY" },
  { id: 338, network: "AIRTEL", network_id: 4, planType: "SME", amount: 140.0, size: "300.0 MB", validity: "2DAY" },
  { id: 192, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 3500.0, size: "6.0 GB", validity: "7 DAYS" },
  { id: 146, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 800.0, size: "2.0 GB", validity: "2 DAYS" },
  { id: 305, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 150.0, size: "100.0 MB", validity: "1 Month" },
  { id: 247, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 2200.0, size: "2.0 GB", validity: "30DAYS" },
  { id: 244, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 600.0, size: "500.0 MB", validity: "30DAYS" },
  { id: 308, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 550.0, size: "750.0 MB", validity: "7 DAYS" },
  { id: 250, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 10000.0, size: "10.0 GB", validity: "1MONTH" },
  { id: 339, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 200.0, size: "150.0 MB", validity: "1Day" },
  { id: 165, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 9700.0, size: "40.0 GB", validity: "30 days" },
  { id: 377, network: "AIRTEL", network_id: 4, planType: "SME", amount: 400.0, size: "1.0 GB", validity: "2DAY" },
  { id: 327, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 4750.0, size: "18.0 GB", validity: "1 Month" },
  { id: 345, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 15000.0, size: "15.0 GB", validity: "30 Days" },
  { id: 193, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 20000.0, size: "110.0 GB", validity: "30 days" },
  { id: 248, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 300.0, size: "300.0 MB", validity: "1MONTH" },
  { id: 342, network: "AIRTEL", network_id: 4, planType: "SME", amount: 2500.0, size: "7.0 GB", validity: "7DAY" },
  { id: 148, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 3000.0, size: "4.5 GB", validity: "30 days" },
  { id: 306, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 20000.0, size: "120.0 GB", validity: "1 Month" },
  { id: 344, network: "AIRTEL", network_id: 4, planType: "SME", amount: 250.0, size: "600.0 MB", validity: "2DAY" },
  { id: 251, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 20000.0, size: "20.0 GB", validity: "1MONTH" },
  { id: 354, network: "AIRTEL", network_id: 4, planType: "SME", amount: 1200.0, size: "3.0 GB", validity: "7DAY" },
  { id: 191, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 14600.0, size: "75.0 GB", validity: "30 days" },
  { id: 304, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 4200.0, size: "10.0 GB", validity: "1 Month" },
  { id: 246, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 150.0, size: "100.0 MB", validity: "1MONTH" },
  { id: 245, network: "AIRTEL", network_id: 4, planType: "CORPORATE GIFTING", amount: 1100.0, size: "1.0 GB", validity: "1MONTH" },
  { id: 145, network: "AIRTEL", network_id: 4, planType: "GIFTING", amount: 850.0, size: "1.0 GB", validity: "7 DAYS" },

  // GLO
  { id: 421, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 3500.0, size: "10.0 GB", validity: "7DAYS" },
  { id: 425, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 1300.0, size: "3.0 GB", validity: "3Day" },
  { id: 256, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 450.0, size: "1.0 GB", validity: "30 days" },
  { id: 419, network: "GLO", network_id: 2, planType: "GIFTING", amount: 3950.0, size: "13.25 GB", validity: "30DAYS" },
  { id: 358, network: "GLO", network_id: 2, planType: "GIFTING", amount: 9800.0, size: "50.0 GB", validity: "30 DAYS" },
  { id: 259, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 2250.0, size: "5.0 GB", validity: "30 days" },
  { id: 346, network: "GLO", network_id: 2, planType: "GIFTING", amount: 490.0, size: "1.05 GB", validity: "7 days" },
  { id: 426, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 2200.0, size: "5.0 GB", validity: "7days" },
  { id: 197, network: "GLO", network_id: 2, planType: "GIFTING", amount: 1950.0, size: "6.25 GB", validity: "30days" },
  { id: 422, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 150.0, size: "200.0 MB", validity: "14DAYs" },
  { id: 424, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 400.0, size: "1.0 GB", validity: "7days" },
  { id: 257, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 900.0, size: "2.0 GB", validity: "30 days" },
  { id: 357, network: "GLO", network_id: 2, planType: "GIFTING", amount: 7400.0, size: "29.05 GB", validity: "30 DAYS" },
  { id: 355, network: "GLO", network_id: 2, planType: "GIFTING", amount: 2900.0, size: "10.0 GB", validity: "30 DAYS" },
  { id: 255, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 250.0, size: "500.0 MB", validity: "30 days" },
  { id: 348, network: "GLO", network_id: 2, planType: "GIFTING", amount: 1900.0, size: "5.8 GB", validity: "30 DAYS" },
  { id: 423, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 370.0, size: "3.0 GB", validity: "3Days" },
  { id: 240, network: "GLO", network_id: 2, planType: "GIFTING", amount: 980.0, size: "2.6 GB", validity: "30 days" },
  { id: 418, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 150.0, size: "200.0 MB", validity: "30Days" },
  { id: 359, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 4500.0, size: "10.0 GB", validity: "30 DAYS" },
  { id: 258, network: "GLO", network_id: 2, planType: "CORPORATE GIFTING", amount: 1350.0, size: "3.0 GB", validity: "30 days" },
  { id: 356, network: "GLO", network_id: 2, planType: "GIFTING", amount: 4800.0, size: "16.0 GB", validity: "30 DAYS" },
  { id: 427, network: "GLO", network_id: 2, planType: "GIFTING", amount: 350.0, size: "1.0 GB", validity: "3DAYS" },
  { id: 241, network: "GLO", network_id: 2, planType: "GIFTING", amount: 2450.0, size: "7.7 GB", validity: "1MONTH" },

  // MTN
  { id: 414, network: "MTN", network_id: 1, planType: "GIFTING", amount: 1800.0, size: "3.5 GB", validity: "7days" },
  { id: 406, network: "MTN", network_id: 1, planType: "GIFTING", amount: 750.0, size: "1.5 GB", validity: "2days" },
  { id: 398, network: "MTN", network_id: 1, planType: "GIFTING", amount: 36000.0, size: "165.0 GB", validity: "30DAYS" },
  { id: 390, network: "MTN", network_id: 1, planType: "GIFTING", amount: 1600.0, size: "2.0 GB", validity: "30days" },
  { id: 388, network: "MTN", network_id: 1, planType: "GIFTING", amount: 28000.0, size: "90.0 GB", validity: "60Days" },
  { id: 311, network: "MTN", network_id: 1, planType: "DATA COUPONS", amount: 750.0, size: "3.0 GB", validity: "1MONTH" },
  { id: 291, network: "MTN", network_id: 1, planType: "CORPORATE GIFTING", amount: 2100.0, size: "3.0 GB", validity: "1 MONTH" },
  { id: 218, network: "MTN", network_id: 1, planType: "SME", amount: 450.0, size: "500.0 MB", validity: "1month" },
  { id: 393, network: "MTN", network_id: 1, planType: "GIFTING", amount: 850.0, size: "1.2 GB", validity: "7days" },
  { id: 385, network: "MTN", network_id: 1, planType: "GIFTING", amount: 1000.0, size: "2.0 GB", validity: "2DAYS" },
  { id: 315, network: "MTN", network_id: 1, planType: "GOOD GOD DATA", amount: 450.0, size: "500.0 MB", validity: "1MONTH" },
  { id: 384, network: "MTN", network_id: 1, planType: "GIFTING", amount: 550.0, size: "1.0 GB", validity: "1DAY" },
  { id: 381, network: "MTN", network_id: 1, planType: "GIFTING", amount: 20000.0, size: "75.0 GB", validity: "30 Days" },
  { id: 417, network: "MTN", network_id: 1, planType: "GIFTING", amount: 450.0, size: "500.0 MB", validity: "1DAY" },
  { id: 409, network: "MTN", network_id: 1, planType: "GIFTING", amount: 10000.0, size: "20.0 GB", validity: "30DAYS" },
  { id: 401, network: "MTN", network_id: 1, planType: "GIFTING", amount: 2800.0, size: "3.5 GB", validity: "30DAYS" },
  { id: 412, network: "MTN", network_id: 1, planType: "GIFTING", amount: 6000.0, size: "20.0 GB", validity: "7days" },
  { id: 404, network: "MTN", network_id: 1, planType: "GIFTING", amount: 120.0, size: "110.0 MB", validity: "1DAY" },
  { id: 396, network: "MTN", network_id: 1, planType: "GIFTING", amount: 55000.0, size: "250.0 GB", validity: "30DAYS" },
  { id: 379, network: "MTN", network_id: 1, planType: "GIFTING", amount: 1100.0, size: "1.5 GB", validity: "7 Days" },
  { id: 318, network: "MTN", network_id: 1, planType: "GOOD GOD DATA", amount: 300000.0, size: "10.0 GB", validity: "1MONTH" },
  { id: 329, network: "MTN", network_id: 1, planType: "DATA COUPONS", amount: 290.0, size: "1.0 GB", validity: "7days" },
  { id: 219, network: "MTN", network_id: 1, planType: "SME", amount: 7500.0, size: "10.0 GB", validity: "1MONTH" },
  { id: 293, network: "MTN", network_id: 1, planType: "CORPORATE GIFTING", amount: 3500.0, size: "5.0 GB", validity: "1 MONTH" },
  { id: 415, network: "MTN", network_id: 1, planType: "GIFTING", amount: 18000.0, size: "65.0 GB", validity: "30DAYS" },
  { id: 407, network: "MTN", network_id: 1, planType: "GIFTING", amount: 1100.0, size: "1.5 GB", validity: "7days" },
  { id: 399, network: "MTN", network_id: 1, planType: "GIFTING", amount: 51000.0, size: "200.0 GB", validity: "60DAYS" },
  { id: 391, network: "MTN", network_id: 1, planType: "GIFTING", amount: 3500.0, size: "6.75 GB", validity: "30DAYS" },
  { id: 383, network: "MTN", network_id: 1, planType: "GIFTING", amount: 10000.0, size: "40.0 GB", validity: "30 Days" },
  { id: 313, network: "MTN", network_id: 1, planType: "GOOD GOD DATA", amount: 700.0, size: "1.0 GB", validity: "1MONTH" },
  { id: 286, network: "MTN", network_id: 1, planType: "CORPORATE GIFTING", amount: 400.0, size: "500.0 MB", validity: "1 MONTH" },
  { id: 295, network: "MTN", network_id: 1, planType: "CORPORATE GIFTING", amount: 700.0, size: "1.0 GB", validity: "1 week" },
  { id: 410, network: "MTN", network_id: 1, planType: "GIFTING", amount: 4000.0, size: "7.0 GB", validity: "30DAYS" },
  { id: 402, network: "MTN", network_id: 1, planType: "GIFTING", amount: 7000.0, size: "12.5 GB", validity: "30DAYS" },
  { id: 394, network: "MTN", network_id: 1, planType: "GIFTING", amount: 1100.0, size: "3.2 GB", validity: "2DAYS" },
  { id: 386, network: "MTN", network_id: 1, planType: "GIFTING", amount: 950.0, size: "1.0 GB", validity: "7DAYS" },
  { id: 316, network: "MTN", network_id: 1, planType: "GOOD GOD DATA", amount: 2100.0, size: "3.0 GB", validity: "1MONTH" },
  { id: 428, network: "MTN", network_id: 1, planType: "SME", amount: 700.0, size: "1.0 GB", validity: "1MONTH" },
  { id: 360, network: "MTN", network_id: 1, planType: "SME", amount: 3500.0, size: "5.0 GB", validity: "30DAYS" },
  { id: 413, network: "MTN", network_id: 1, planType: "GIFTING", amount: 3500.0, size: "6.0 GB", validity: "7days" },
  { id: 405, network: "MTN", network_id: 1, planType: "GIFTING", amount: 100.0, size: "75.0 MB", validity: "1DAY" },
  { id: 397, network: "MTN", network_id: 1, planType: "GIFTING", amount: 8000.0, size: "35.0 GB", validity: "30DAYS" },
  { id: 389, network: "MTN", network_id: 1, planType: "GIFTING", amount: 1000.0, size: "2.5 GB", validity: "2Days" },
  { id: 322, network: "MTN", network_id: 1, planType: "DATA COUPONS", amount: 200.0, size: "750.0 MB", validity: "1MONTH" },
  { id: 310, network: "MTN", network_id: 1, planType: "DATA COUPONS", amount: 600.0, size: "2.0 GB", validity: "1MONTH" },
  { id: 214, network: "MTN", network_id: 1, planType: "SME", amount: 700.0, size: "1.0 GB", validity: "1week" },
  { id: 216, network: "MTN", network_id: 1, planType: "SME", amount: 2100.0, size: "3.0 GB", validity: "30DAYS" },
  { id: 314, network: "MTN", network_id: 1, planType: "GOOD GOD DATA", amount: 1400.0, size: "2.0 GB", validity: "1MONTH" },
  { id: 333, network: "MTN", network_id: 1, planType: "GOOD GOD DATA", amount: 50.0, size: "100.0 MB", validity: "30 Days" },
  { id: 380, network: "MTN", network_id: 1, planType: "GIFTING", amount: 7500.0, size: "16.5 GB", validity: "30 Days" },
  { id: 416, network: "MTN", network_id: 1, planType: "GIFTING", amount: 6000.0, size: "14.5 GB", validity: "30 Days" },
  { id: 408, network: "MTN", network_id: 1, planType: "GIFTING", amount: 10500.0, size: "25.0 GB", validity: "30DAYS" },
  { id: 400, network: "MTN", network_id: 1, planType: "GIFTING", amount: 500.0, size: "500.0 MB", validity: "7days" },
  { id: 392, network: "MTN", network_id: 1, planType: "GIFTING", amount: 2100.0, size: "2.7 GB", validity: "30DAYS" },
  { id: 387, network: "MTN", network_id: 1, planType: "GIFTING", amount: 550.0, size: "750.0 MB", validity: "3DAYS" },
  { id: 411, network: "MTN", network_id: 1, planType: "GIFTING", amount: 130000.0, size: "800.0 GB", validity: "1YEAR" },
  { id: 403, network: "MTN", network_id: 1, planType: "GIFTING", amount: 250.0, size: "230.0 MB", validity: "1DAY" },
  { id: 395, network: "MTN", network_id: 1, planType: "GIFTING", amount: 12000.0, size: "36.0 GB", validity: "30DAYS" },
  { id: 382, network: "MTN", network_id: 1, planType: "GIFTING", amount: 6000.0, size: "10.0 GB", validity: "30 Days" },
  { id: 320, network: "MTN", network_id: 1, planType: "GOOD GOD DATA", amount: 3500.0, size: "5.0 GB", validity: "1MONTH" },
  { id: 285, network: "MTN", network_id: 1, planType: "CORPORATE GIFTING", amount: 1400.0, size: "2.0 GB", validity: "1 week" },
  { id: 215, network: "MTN", network_id: 1, planType: "SME", amount: 1400.0, size: "2.0 GB", validity: "1MONTH" }
]


const electricityPlanList = [
  { serviceCode: "aba-electric", displayName: "Aba Electricity Distribution Company" },
  { serviceCode: "abuja-electric", displayName: "Abuja Electricity Distribution Company" },
  { serviceCode: "benin-electric", displayName: "Benin Electricity Distribution Company" },
  { serviceCode: "eko-electric", displayName: "Eko Electricity Distribution Company" },
  { serviceCode: "enugu-electric", displayName: "Enugu Electricity Distribution Company" },
  { serviceCode: "ibadan-electric", displayName: "Ibadan Electricity Distribution Company" },
  { serviceCode: "ikeja-electric", displayName: "Ikeja Electricity Distribution Company" },
  { serviceCode: "jos-electric", displayName: "Jos Electricity Distribution Company" },
  { serviceCode: "kaduna-electric", displayName: "Kaduna Electricity Distribution Company" },
  { serviceCode: "kano-electric", displayName: "Kano Electricity Distribution Company" },
  { serviceCode: "portharcourt-electric", displayName: "Port Harcourt Electricity Distribution Company" },
  { serviceCode: "yola-electric", displayName: "Yola Electricity Distribution Company" }
]

const cablePlans = [
  { name: "gotv_smallie", price: 1900 },
  { name: "gotv_smallie_3months", price: 5100 },
  { name: "gotv_smallie_1year", price: 15000 },
  { name: "gotv_jinja", price: 3900 },
  { name: "gotv_jolli", price: 5800 },
  { name: "gotv_max", price: 8500 },
  { name: "dstv_padi", price: 4400 },
  { name: "dstv_yanga", price: 6000 },
  { name: "dstv_confam", price: 11000 },
  { name: "dstv_compact", price: 19000 },
  { name: "dstv_compact_plus", price: 30000 },
  { name: "dstv_premium", price: 44500 },
  { name: "dstv_asia", price: 14900 },
  { name: "dstv_premium_french", price: 69000 },
  { name: "startimes_nova_daily", price: 0.0 },
  { name: "startimes_nova_weekly", price: 600 },
  { name: "startimes_nova", price: 1900 },
  { name: "startimes_basic_daily", price: 0.0 },
  { name: "startimes_basic_weekly", price: 1250 },
  { name: "startimes_basic", price: 3700 },
  { name: "startimes_smart_daily", price: 0.0 },
  { name: "startimes_smart_weekly", price: 1550 },
  { name: "startimes_smart", price: 4700 },
  { name: "startimes_classic_daily", price: 0.0 },
  { name: "startimes_classic_weekly", price: 1900 },
  { name: "startimes_classic", price: 5500 },
  { name: "startimes_super_daily", price: 0.0 },
  { name: "startimes_super_weekly", price: 3000 },
  { name: "startimes_super", price: 9000 },
  { name: "startimes_unique_daily", price: 0.0 },
  { name: "startimes_unique_weekly", price: 0.0 },
  { name: "startimes_unique", price: 0.0 },
]

const resultCheckerPlans = [
  { description: "WAEC Result Checking PIN", service: "waec", code: 1, price: 3850 },
  { description: "WAEC GCE Registration PIN", service: "waec", code: 2, price: 24000 },
  { description: "WAEC Verification PIN", service: "waec", code: 3, price: 3850 },
  { description: "NECO Result Checking Token", service: "neco", code: 1, price: 1250 },
  { description: "NECO GCE Registration PIN", service: "neco", code: 2, price: 1250 },
  { description: "NABTEB Result Checking PIN", service: "nabteb", code: 1, price: 1200 },
  { description: "NABTEB GCE Registration PIN", service: "nabteb", code: 2, price: 1200 },
  { description: "JAMB UTME Registration PIN", service: "jamb", code: 1, price: 7150 },
  { description: "JAMB Direct Entry Registration PIN", service: "jamb", code: 2, price: 5600 },
]

export { dataPlans, electricityPlanList, cablePlans, resultCheckerPlans }
